export interface ChunkMeta {
  id: string;
  name: string;
  description: string;
  filename: string;
  keywords: string[];
}

export const CHUNKS: ChunkMeta[] = [
  {
    id: "overview-and-setup",
    name: "Overview & Setup",
    description:
      "SDK overview, installation, basic usage pattern, create_daemon factory function, context manager, public API exports",
    filename: "01-overview-and-setup.md",
    keywords: [
      "overview",
      "install",
      "setup",
      "create_daemon",
      "factory",
      "import",
      "lucidlink",
      "wheel",
      "pip",
      "getting started",
      "exports",
      "public api",
      "context manager",
      "filespace.fs",
      "basic usage",
    ],
  },
  {
    id: "daemon-and-authentication",
    name: "Daemon & Authentication",
    description:
      "Daemon lifecycle, create_daemon factory, ServiceAccountCredentials, StorageConfig, StorageMode, DaemonStatus dataclass, get_status, configuration keys",
    filename: "02-daemon-and-authentication.md",
    keywords: [
      "daemon",
      "create_daemon",
      "start",
      "stop",
      "authenticate",
      "credentials",
      "ServiceAccountCredentials",
      "token",
      "sa_live",
      "lucid_sa",
      "storage",
      "StorageConfig",
      "StorageMode",
      "sandboxed",
      "physical",
      "persist",
      "cache",
      "singleton",
      "get_status",
      "DaemonStatus",
      "is_running",
      "is_authenticated",
      "is_linked",
      "root_path",
      "config",
      "webservice",
    ],
  },
  {
    id: "workspace-and-filespace",
    name: "Workspace, Filespace & Filesystem",
    description:
      "Workspace methods, Filespace properties (fs, connect, sync_all, unlink, context manager), Filesystem class file/directory operations (open, read_dir, list_dir, create_dir, move, truncate, byte range locking), DirEntry and FilespaceInfo models",
    filename: "03-workspace-and-filespace.md",
    keywords: [
      "workspace",
      "filespace",
      "filesystem",
      "filespace.fs",
      "link_filespace",
      "list_filespaces",
      "open",
      "open_legacy",
      "read_dir",
      "list_dir",
      "create_dir",
      "delete_dir",
      "dir_exists",
      "read_file",
      "write_file",
      "delete",
      "file_exists",
      "get_entry",
      "get_size",
      "get_statistics",
      "sync_all",
      "unlink",
      "lock_type",
      "mode",
      "buffering",
      "move",
      "rename",
      "truncate",
      "create",
      "lock_byte_range",
      "unlock_byte_range",
      "unlock_all_byte_ranges",
      "byte range",
      "sync",
      "flush",
      "FileHandle",
      "Filesystem",
      "DirEntry",
      "FilespaceInfo",
      "context manager",
    ],
  },
  {
    id: "streaming-and-file-io",
    name: "Streaming & File I/O",
    description:
      "LucidFileStream (io.RawIOBase), buffering options, text encoding, file locking, large file streaming, open_buffered, open_text, performance tips",
    filename: "04-streaming-and-file-io.md",
    keywords: [
      "stream",
      "streaming",
      "LucidFileStream",
      "RawIOBase",
      "read",
      "write",
      "seek",
      "tell",
      "truncate",
      "readinto",
      "fileno",
      "isatty",
      "buffering",
      "BufferedReader",
      "BufferedWriter",
      "BufferedRandom",
      "TextIOWrapper",
      "encoding",
      "text",
      "binary",
      "lock",
      "locking",
      "chunk",
      "large file",
      "performance",
      "open_buffered",
      "open_text",
      "lock_type",
    ],
  },
  {
    id: "connect-external-files",
    name: "Connect (External Files)",
    description:
      "ConnectManager, S3DataStoreConfig, S3Credentials, DataStoreCredentials, DataStoreInfo, DataStoreKind, DataStoreRekeyState, LinkedFilesResult, link/unlink external files, data store management, S3 integration",
    filename: "05-connect-external-files.md",
    keywords: [
      "connect",
      "ConnectManager",
      "S3DataStoreConfig",
      "S3Credentials",
      "DataStoreCredentials",
      "DataStoreInfo",
      "DataStoreKind",
      "DataStoreRekeyState",
      "LinkedFilesResult",
      "add_data_store",
      "remove_data_store",
      "list_data_stores",
      "get_data_store",
      "rekey_data_store",
      "link_file",
      "unlink_file",
      "list_external_files",
      "count_external_files",
      "are_data_stores_available",
      "cursor",
      "size",
      "checksum",
      "s3",
      "bucket",
      "external",
      "presigned",
      "endpoint",
      "minio",
    ],
  },
  {
    id: "fsspec-integration",
    name: "fsspec Integration",
    description:
      "LucidLinkFileSystem (fsspec), Pandas URL-based access, Dask, storage_options, SyncMode, get/put/mv/rename, sync_all, close",
    filename: "06-fsspec-integration.md",
    keywords: [
      "fsspec",
      "LucidLinkFileSystem",
      "storage_options",
      "pandas",
      "dask",
      "pyarrow",
      "lucidlink://",
      "url",
      "SyncMode",
      "ls",
      "info",
      "exists",
      "mkdir",
      "makedirs",
      "glob",
      "find",
      "du",
      "cp",
      "mv",
      "rename",
      "rm",
      "cat",
      "cat_file",
      "pipe",
      "touch",
      "get",
      "put",
      "sync_all",
      "close",
      "webservice_url",
      "LucidLinkOptions",
      "SYNC_ALL",
      "SYNC_NONE",
    ],
  },
  {
    id: "models-and-exceptions",
    name: "Models & Exceptions",
    description:
      "DirEntry, FilespaceInfo, FilespaceSize, FilespaceStatistics, DaemonStatus, enums (StorageMode, SyncMode, DataStoreKind, DataStoreRekeyState), exception hierarchy (LucidLinkError, DaemonError, FilespaceError, AuthenticationError, ConfigurationError)",
    filename: "07-models-and-exceptions.md",
    keywords: [
      "DirEntry",
      "FilespaceInfo",
      "FilespaceSize",
      "FilespaceStatistics",
      "DaemonStatus",
      "StorageMode",
      "SyncMode",
      "DataStoreKind",
      "DataStoreRekeyState",
      "exception",
      "error",
      "LucidLinkError",
      "DaemonError",
      "FilespaceError",
      "AuthenticationError",
      "ConfigurationError",
    ],
  },
  {
    id: "examples-and-integrations",
    name: "Examples & Integrations",
    description:
      "Code examples mirroring the upstream examples repo: quickstart, file operations, file locking, Connect S3, fsspec operations, fsspec + pandas, llconnect reference tool",
    filename: "08-examples-and-integrations.md",
    keywords: [
      "example",
      "quickstart",
      "pandas",
      "csv",
      "parquet",
      "fsspec",
      "llconnect",
      "json",
      "jsonl",
      "write_file",
      "read_file",
      "list_dir",
      "read_dir",
      "create_dir",
      "delete",
      "move",
      "get_entry",
    ],
  },
  {
    id: "file-locking",
    name: "File Locking",
    description:
      "On-open locking (lock_type shared/exclusive), byte-range locking API, when to use which approach",
    filename: "10-file-locking.md",
    keywords: [
      "lock",
      "locking",
      "lock_type",
      "shared",
      "exclusive",
      "lock_byte_range",
      "unlock_byte_range",
      "unlock_all_byte_ranges",
      "byte range",
      "blocking",
      "non-blocking",
      "reader",
      "writer",
      "file lock",
    ],
  },
  {
    id: "quick-reference",
    name: "Quick Reference",
    description:
      "Compact API cheat sheet: every class, method signature, and one-liner for Daemon, Workspace, Filespace, Filesystem, LucidFileStream, ConnectManager, fsspec, models, exceptions, URL parser",
    filename: "11-quick-reference.md",
    keywords: [
      "reference",
      "cheat sheet",
      "api",
      "signature",
      "method",
      "class",
      "summary",
      "quick",
      "lookup",
      "all methods",
      "all classes",
      "overview",
      "list",
    ],
  },
  {
    id: "configuration-and-sync",
    name: "Configuration & Sync Best Practices",
    description:
      "sync_all() rule, storage modes (sandboxed vs physical), context manager pattern, fsspec sync behavior, one daemon per process",
    filename: "12-configuration-and-sync.md",
    keywords: [
      "sync_all",
      "sync",
      "configuration",
      "config",
      "storage mode",
      "sandboxed",
      "physical",
      "persist",
      "context manager",
      "SyncMode",
      "unlink",
      "cleanup",
      "root_path",
      "persist_files",
    ],
  },
];
