export interface ChunkMeta {
  id: string;
  name: string;
  description: string;
  filename: string;
  keywords: string[];
}

export const CHUNKS: ChunkMeta[] = [
  {
    id: "overview-and-setup",
    name: "Overview & Setup",
    description:
      "SDK overview, installation, basic usage pattern, factory function, public API exports",
    filename: "01-overview-and-setup.md",
    keywords: [
      "overview",
      "install",
      "setup",
      "create_daemon",
      "factory",
      "import",
      "lucidlink",
      "wheel",
      "pip",
      "getting started",
      "exports",
      "public api",
      "context manager",
    ],
  },
  {
    id: "daemon-and-authentication",
    name: "Daemon & Authentication",
    description:
      "Daemon lifecycle, ServiceAccountCredentials, StorageConfig, StorageMode, configuration keys, get_status",
    filename: "02-daemon-and-authentication.md",
    keywords: [
      "daemon",
      "start",
      "stop",
      "authenticate",
      "credentials",
      "ServiceAccountCredentials",
      "token",
      "sa_live",
      "storage",
      "StorageConfig",
      "StorageMode",
      "sandboxed",
      "physical",
      "persist",
      "cache",
      "singleton",
      "get_status",
      "is_running",
      "config",
      "webservice",
    ],
  },
  {
    id: "workspace-and-filespace",
    name: "Workspace & Filespace",
    description:
      "Workspace methods, Filespace file/directory operations, open(), read_dir, create_dir, move, truncate, byte range locking, sync_all",
    filename: "03-workspace-and-filespace.md",
    keywords: [
      "workspace",
      "filespace",
      "link_filespace",
      "list_filespaces",
      "open",
      "read_dir",
      "create_dir",
      "delete_dir",
      "dir_exists",
      "read_file",
      "write_file",
      "delete",
      "file_exists",
      "get_entry",
      "get_size",
      "get_filespace_size",
      "get_filespace_statistics",
      "sync_all",
      "lock_type",
      "mode",
      "buffering",
      "move",
      "rename",
      "truncate",
      "lock_byte_range",
      "unlock_byte_range",
      "byte range",
      "sync",
      "flush",
    ],
  },
  {
    id: "streaming-and-file-io",
    name: "Streaming & File I/O",
    description:
      "LucidFileStream, io.RawIOBase, buffering, text encoding, file locking, large file streaming, performance tips",
    filename: "04-streaming-and-file-io.md",
    keywords: [
      "stream",
      "streaming",
      "LucidFileStream",
      "RawIOBase",
      "read",
      "write",
      "seek",
      "tell",
      "truncate",
      "buffering",
      "BufferedReader",
      "BufferedWriter",
      "TextIOWrapper",
      "encoding",
      "text",
      "binary",
      "lock",
      "locking",
      "chunk",
      "large file",
      "performance",
      "open_buffered",
      "open_text",
    ],
  },
  {
    id: "connect-external-files",
    name: "Connect (External Files)",
    description:
      "ConnectManager, S3DataStoreConfig, DataStoreInfo, LinkedFilesResult, link/unlink files, data store management",
    filename: "05-connect-external-files.md",
    keywords: [
      "connect",
      "ConnectManager",
      "S3DataStoreConfig",
      "DataStoreInfo",
      "LinkedFilesResult",
      "add_data_store",
      "remove_data_store",
      "list_data_stores",
      "get_data_store",
      "rekey_data_store",
      "link_file",
      "unlink_file",
      "list_external_files",
      "count_external_files",
      "s3",
      "bucket",
      "external",
      "presigned",
      "endpoint",
      "minio",
    ],
  },
  {
    id: "fsspec-integration",
    name: "fsspec Integration",
    description:
      "LucidLinkFileSystem, fsspec, Pandas URL-based access, Dask, storage_options, SyncMode",
    filename: "06-fsspec-integration.md",
    keywords: [
      "fsspec",
      "LucidLinkFileSystem",
      "storage_options",
      "pandas",
      "dask",
      "pyarrow",
      "lucidlink://",
      "url",
      "SyncMode",
      "ls",
      "info",
      "exists",
      "mkdir",
      "glob",
      "find",
      "du",
      "cp",
      "mv",
      "rm",
      "cat",
      "pipe",
      "touch",
    ],
  },
  {
    id: "models-and-exceptions",
    name: "Models & Exceptions",
    description:
      "FileEntry, FilespaceSize, FilespaceStatistics, exception hierarchy, error handling, URL parser, file modes",
    filename: "07-models-and-exceptions.md",
    keywords: [
      "FileEntry",
      "FilespaceSize",
      "FilespaceStatistics",
      "exception",
      "error",
      "LucidLinkError",
      "DaemonError",
      "FilespaceError",
      "AuthenticationError",
      "ConfigurationError",
      "FileNotFoundError",
      "PermissionError",
      "ParsedUrl",
      "UrlParser",
      "file_modes",
    ],
  },
  {
    id: "examples-and-integrations",
    name: "Examples & Integrations",
    description:
      "Code examples: basic streaming, Pandas, PyTorch, NumPy, LangChain, Hugging Face, LLConnect CLI",
    filename: "08-examples-and-integrations.md",
    keywords: [
      "example",
      "pandas",
      "csv",
      "parquet",
      "excel",
      "pytorch",
      "torch",
      "numpy",
      "langchain",
      "hugging face",
      "transformers",
      "dataset",
      "dataloader",
      "checkpoint",
      "model",
      "llconnect",
      "cli",
      "mirror",
      "link",
      "unlink",
      "store",
      "json",
      "jsonl",
    ],
  },
  {
    id: "limitations-and-performance",
    name: "Known Limitations & Performance",
    description:
      "Concurrency constraints, thread safety, hub-level locking, max_concurrent_writes, sync_all timing, SDK vs desktop benchmarks, optimization strategies",
    filename: "09-limitations-and-performance.md",
    keywords: [
      "concurrent",
      "concurrency",
      "thread",
      "threading",
      "parallel",
      "multiprocessing",
      "performance",
      "benchmark",
      "limitation",
      "constraint",
      "LockingException",
      "max_concurrent_writes",
      "file handle",
      "race condition",
      "thread safety",
      "sync_all",
      "consistency",
      "hub",
      "crash",
      "retry",
      "worker",
      "throughput",
      "latency",
      "cache",
      "optimization",
      "slow",
      "fast",
      "speed",
    ],
  },
];
